### ISSUE TITLE
Multiple pack files during "select a Pack file", needs more descriptors

### ISSUE THREAD

**Issue by rgmoorer** [PhaserEditor2D/PhaserEditor#139] opened 2019-12-25 09:31 UTC
## Version

* Phaser Editor Version: 2.1.5.20191125

* Operating system: Windows 10 Home

## Description
- Multiple pack files in separate folders all named "pack.json"
- Create a new asset (atlas file, animation file, etc)
- On the step that has you select which pack file to add the asset to, all pack files are listed as "pack.json" with no other descriptors.
- This makes it impossible to choose the correct pack file to add the asset to.

## Possible solution
Add folder paths to the listing, for example:
folder1/pack.json
folder2/pack.json
folder3/pack.json

This way the root folder name can differentiate the pack files, allowing identical pack file names.

**Comment by PhaserEditor2D** [comment] 2019-12-25 22:00
Hi @rgmoorer is not this a duplicate of #138 ?

We provided a patch, what I think is missing is this: https://github.com/PhaserEditor2D/PhaserEditor/issues/138#issuecomment-563107804

**Comment by rgmoorer** [comment] 2019-12-27 09:02
I don't believe this is a duplicate, because prefixes are not added to pack files as far as I know.

**Comment by PhaserEditor2D** [comment] 2019-12-27 13:30
Oh! you are right! Sorry, I don't know what I read.

Do you mean something like this?

![image](https://user-images.githubusercontent.com/12187299/71518882-0d77c000-2883-11ea-88cf-506a843411cd.png)

Let me work on the other issue (https://github.com/PhaserEditor2D/PhaserEditor/issues/138#issuecomment-563107804) to upload a new patch.

**Comment by PhaserEditor2D** [comment] 2019-12-27 13:33
Or better this, without the `WebContent` element, that should be common to all the pack files:

![image](https://user-images.githubusercontent.com/12187299/71519016-942c9d00-2883-11ea-8262-106f886344c8.png)

**Comment by PhaserEditor2D** [comment] 2019-12-27 15:39
This change is included in the patch attached here: https://github.com/PhaserEditor2D/PhaserEditor/issues/138#issuecomment-569293175
Please, test it and tell me if it is working.

**Closed** 2019-12-31 04:08 UTC
