### ISSUE TITLE
suggest support text

### ISSUE THREAD

**Issue by 1078559858** [PhaserEditor2D/PhaserEditor#53] opened 2017-09-29 02:12 UTC
if editor could add a text ,that will let me save a lot of time.
the text founction could could be less, could hava postion, size, anchor  property.

**Comment by boniatillo-com** [comment] 2017-09-29 13:12
Duplicate of  https://github.com/boniatillo-com/PhaserEditor/issues/27

**Closed** 2018-01-30 21:21 UTC
Labels: duplicate
