### ISSUE TITLE
mklink - command (alias folder), unable to "Building Phaser documentation model"

### ISSUE THREAD

**Issue by weekendkoder** [PhaserEditor2D/PhaserEditor#97] opened 2019-01-16 18:25 UTC
## Version

* Phaser Editor Version: 2.0

* Operating system: Windows 8.1

## Description

I encountered a small-problem. It comes up, 

when i start PhaserEditor. I think it happens, because i made PhaserEditor more-"portable" and or i like to have my windows-partition clean. Therefore i used the "very usefull" command: "**mklink**" (makes aliases of folders)

_my command for PhaserEditor:_
Mklink /d "C:\Users\%USERNAME%\.phasereditor" "%cd%\_phasereditor_CURRENT-USER"
(in my case, it stores a file there, named: "phaser.json.1546967567000.binary")

Everything what would be stored onto C: will be redirected to my defined folder. Thats it. Pretty simple, to keep a clean OS disk. My method works with many many Apps i have installed (99% everything works with this method). So my question is, is that file "phaser.json.1546967567000.binary" nescecary ? Could it be stored in a subfolder of the PE2Dv2.0 install? Or maybe somebody could try my method out with its PE2Dv2.0 install. And if you got the same error, maybe you found a solution you can post here. Would be great !

**Comment by PhaserEditor2D** [comment] 2019-01-16 20:56
I can reproduce the error. The problem is the routine `Files.createDirectories()` does not recognize the link as a directory, so first I should check if it exists.

However, there is something you can do. 

Open the `PhaserEditor2D.ini` file and add this line at the end:

`-Duser.home=x:/path/to/the/new/home`

It is working for me. To write the path, use the `"/"` instead of the `"\"`.

Please test it and if it works, close this.

**Comment by PhaserEditor2D** [comment] 2019-01-17 16:12
Then I close this. You are welcome!

**Closed by PhaserEditor2D** 2019-01-17 16:12 UTC
Labels: bug
